### ISSUE TITLE
where the pre-training model of 'retinanet_se50.pth' to download

### ISSUE THREAD

**Issue by tc-qaq** [qjadud1994/OCR_Detector#2]
Hi @qjadud1994
I need a pre-train model imagenet_pretrain = 'weights/retinanet_se50.pth' in train.py 
but no url to download this model
Could you list the url of this model,thanks

**Comment by qjadud1994** [comment]
please check [this link](https://github.com/qjadud1994/Text_Detector/tree/master/Tensorflow/weights)

**Comment by tc-qaq** [comment]
ok,thanks

**Comment by agiokas-dbg** [comment]
So which one is it, because the filenames do not match the output error.

**Comment by cosen1024** [comment]
When I use this pre-train model that you provide ，se-resnet50-bn : https://data.lip6.fr/cadene/pretrainedmodels/se_resnet50-ce0d4300.pth
I meet，RuntimeError: Error(s) in loading state_dict for RetinaNet 
Is this pre-train model wrong?

**Comment by qjadud1994** [comment]
First, you should run
https://github.com/qjadud1994/Text_Detector/blob/master/Pytorch/get_state_dict.py
 .
Then run train.py code.

2019년 12월 1일 (일) 오후 6:38, ssma96 <notifications@github.com>님이 작성:
