### ISSUE TITLE
Training is slow enough

### ISSUE THREAD

**Issue by yy9568** [qjadud1994/OCR_Detector#3]
Thanks for code sharing. ```union_area = MultiPoint(union_poly).convex_hull.area``` ran extremely slowly when I had tried your code on icdar-2015 dataset, one iteration cost more than 20 mins, it's inconceivable. Can u explain why? Thank u again.

**Comment by yy9568** [comment]
@qjadud1994

**Comment by qjadud1994** [comment]
It didn’t take that long time when I trained.
I think you should check ‘shapely’ library.

**Comment by yy9568** [comment]
@qjadud1994 My Version: 1.6.4.post2, may you tell me which version you use in? Thank you so much

**Comment by yy9568** [comment]
@qjadud1994 In fact, the pytorch version can't work, I print some variables of `non_max_suppression_poly`,l such as 
```
iter 0 (epoch 0) || loss: 1309.4976 || l loc_loss: 0.1840 || l cls_loss: 1309.3135 (Time : 2.5)
Get 687960 boxes
1 th boxes
2 th boxes
3 th boxes
```
the `nms algorithm` seems ran slowly extremely, each iteration for `687960` boxes cost several minutes, looking for your reply

**Comment by qjadud1994** [comment]
1. Did you use the ImageNet pre-trained weights?
2. During training, NMS is just to visualize the results of valid images. Modify to visualize after number epoch.
3. Use a high threshold value.

**Comment by jercas** [comment]
> @qjadud1994 In fact, the pytorch version can't work, I print some variables of `non_max_suppression_poly`,l such as
> 
> ```
> iter 0 (epoch 0) || loss: 1309.4976 || l loc_loss: 0.1840 || l cls_loss: 1309.3135 (Time : 2.5)
> Get 687960 boxes
> 1 th boxes
> 2 th boxes
> 3 th boxes
> ```
> 
> the `nms algorithm` seems ran slowly extremely, each iteration for `687960` boxes cost several minutes, looking for your reply

Hi, have you solved the problem? I was stumped by the same question that my program jamed on the "non_max_suppression_poly(quad_boxes, score, self.nms_thresh) --> shapely.Ploygon(box1).convex_hull".
I have try to changed the version of Shapely while i do not know which version is @qjadud1994  used.  By the way, do you know where to get the 'retinanet_se50' pre-trained model ?
Thank you anyway,  I look forward to your reply.

**Comment by speakstone** [comment]
> > @ qjadud1994实际上，pytorch版本无法正常工作，我打印了一些`non_max_suppression_poly`诸如，l之类的变量
> > ```
> > iter 0 (epoch 0) || loss: 1309.4976 || l loc_loss: 0.1840 || l cls_loss: 1309.3135 (Time : 2.5)
> > Get 687960 boxes
> > 1 th boxes
> > 2 th boxes
> > 3 th boxes
> > ```
> > 
> > 
> > 在`nms algorithm`似乎跑慢极了，每次迭代`687960`箱要花好几分钟，期待您的回复
> 
> 嗨，您解决了这个问题吗？我的程序卡在“ non_max_suppression_poly（quad_boxes，score，self.nms_thresh）-> shapely.Ploygon（box1）.convex_hull”这个问题上，使我感到困惑。
> 我不知道@ qjadud1994 使用哪个版本，但是尝试更改Shapely的版本。顺便说一句，您知道从哪里获得“ retinanet_se50”预训练模型吗？
> 无论如何，谢谢您，我期待着您的回复。

Hello, I also have a very slow running problem. How do you solve your problem?

> > @qjadud1994 In fact, the pytorch version can't work, I print some variables of `non_max_suppression_poly`,l such as
> > ```
> > iter 0 (epoch 0) || loss: 1309.4976 || l loc_loss: 0.1840 || l cls_loss: 1309.3135 (Time : 2.5)
> > Get 687960 boxes
> > 1 th boxes
> > 2 th boxes
> > 3 th boxes
> > ```
> > 
> > 
> > the `nms algorithm` seems ran slowly extremely, each iteration for `687960` boxes cost several minutes, looking for your reply
> 
> Hi, have you solved the problem? I was stumped by the same question that my program jamed on the "non_max_suppression_poly(quad_boxes, score, self.nms_thresh) --> shapely.Ploygon(box1).convex_hull".
> I have try to changed the version of Shapely while i do not know which version is @qjadud1994 used. By the way, do you know where to get the 'retinanet_se50' pre-trained model ?
> Thank you anyway, I look forward to your reply.

Hello, I also have a very slow running problem. How do you solve your problem?

**Comment by yy9568** [comment]
Try to use [pyclipper lib](https://github.com/fonttools/pyclipper) with cython, rewrite nms and overlaps module, it will be fast enough.
