### ISSUE TITLE
Would you please offer the 'weights/retinanet_se50.pth' pre-trained model? Thanks!

### ISSUE THREAD

**Issue by jercas** [qjadud1994/OCR_Detector#8]
Thank for your amazing work, firstly. Actually, I have some problem when i trying to train the model on myself plate number dataset. The trackback indicate that the pre-trained model which i download in weights/readme -- se-resnet50-bn.pth does not match to the state-dict. So i am wondering that where can i get the 'retinanet_se50.pth' on your train.py script.
  Looking forward to your reply.

**Comment by qjadud1994** [comment]
you can get pre-trained weight [here](https://github.com/qjadud1994/Text_Detector/tree/master/Tensorflow/weights#imagenet-pre-train-weights-pytorch).

**Comment by jercas** [comment]
> you can get pre-trained weight [here](https://github.com/qjadud1994/Text_Detector/tree/master/Tensorflow/weights#imagenet-pre-train-weights-pytorch).

Thanks for your reply! I already download these pre-trained weight. But when i use se-resnet50 to train there is a backtrack said that "Missing keys in state-dict" and "Unexpected keys in state-dict". I thought may be it is caused by the wrong pre-trained model.  Because i can not find the 'retinanet_se50.pth' pre-trained model which indicated in your python script 'train.py'. In the end, still thanks for your awesome work and wish you can give me some guidance.

**Comment by qjadud1994** [comment]
I think you should execute this [code](https://github.com/qjadud1994/Text_Detector/blob/master/Pytorch/get_state_dict.py) first.

**Comment by jercas** [comment]
> I think you should execute this [code](https://github.com/qjadud1994/Text_Detector/blob/master/Pytorch/get_state_dict.py) first.

Sorry for bother you again. I followed your advice to transform the 'resnet50.pth' to the right dict_state. But when i retrying to running the train scipt, i got a error as follow. 
"
RuntimeError: Error(s) in loading state_dict for RetinaNet:
        size mismatch for cls_head.8.weight: copying a param with shape torch.Size([28, 256, 3, 5]) from checkpoint, the shape in current model is torch.Size([14, 256, 3, 5]).
        size mismatch for cls_head.8.bias: copying a param with shape torch.Size([28]) from checkpoint, the shape in current model is torch.Size([14]).
"

I'm sorry to bother you so many times.

**Comment by qjadud1994** [comment]
I'm sorry.
The code was a version for OHEM+ce Loss that was not supported.

I've updated the [code](https://github.com/qjadud1994/Text_Detector/blob/master/Pytorch/get_state_dict.py). Try again.

**Comment by jercas** [comment]
Truly, truly thanks for your patience! I have succeeded in training this project on my own dataset. Thanks for your guidance all the way. I will continue to study on your project.

BTW: 
I found a little problem when recording by TensorboardX and this may be confuse somebody. 
When i try to recording the image, the different data formats caused a error (default = 'CHW').
May be you can update it.
" writer.add_image('image', img_tensor=infer_img, global_step=iteration, dataformats='HWC') "

In the end, Thanks again~

**Comment by QuickLearner171998** [comment]
@jercas  can you give the exact command that u used for training the model for your dataset.

Thanks
